INSERT INTO `meals`.`meals`
(`idMeal`,
`mealMeal`,
`mealCategory`,
`mealArea`,
`mealInstructions`,
`mealMealThumb`,
`mealTags`,
`mealYoutube`,
`mealIngredient1`,
`mealIngredient2`,
`mealIngredient3`,
`mealIngredient4`,
`mealIngredient5`,
`mealIngredient6`,
`mealIngredient7`,
`mealIngredient8`,
`mealIngredient9`,
`mealIngredient10`,
`mealIngredient11`,
`mealIngredient12`,
`mealIngredient13`,
`mealIngredient14`,
`mealIngredient15`,
`mealIngredient16`,
`mealIngredient17`,
`mealIngredient18`,
`mealIngredient19`,
`mealIngredient20`,
`mealMeasure1`,
`mealMeasure2`,
`mealMeasure3`,
`mealMeasure4`,
`mealMeasure5`,
`mealMeasure6`,
`mealMeasure7`,
`mealMeasure8`,
`mealMeasure9`,
`mealMeasure10`,
`mealMeasure11`,
`mealMeasure12`,
`mealMeasure13`,
`mealMeasure14`,
`mealMeasure15`,
`mealMeasure16`,
`mealMeasure17`,
`mealMeasure18`,
`mealMeasure19`,
`mealMeasure20`,
`mealSource`,
`dateModified`)
VALUES
(<{idMeal: }>,
<{mealMeal: }>,
<{mealCategory: }>,
<{mealArea: }>,
<{mealInstructions: }>,
<{mealMealThumb: }>,
<{mealTags: }>,
<{mealYoutube: }>,
<{mealIngredient1: }>,
<{mealIngredient2: }>,
<{mealIngredient3: }>,
<{mealIngredient4: }>,
<{mealIngredient5: }>,
<{mealIngredient6: }>,
<{mealIngredient7: }>,
<{mealIngredient8: }>,
<{mealIngredient9: }>,
<{mealIngredient10: }>,
<{mealIngredient11: }>,
<{mealIngredient12: }>,
<{mealIngredient13: }>,
<{mealIngredient14: }>,
<{mealIngredient15: }>,
<{mealIngredient16: }>,
<{mealIngredient17: }>,
<{mealIngredient18: }>,
<{mealIngredient19: }>,
<{mealIngredient20: }>,
<{mealMeasure1: }>,
<{mealMeasure2: }>,
<{mealMeasure3: }>,
<{mealMeasure4: }>,
<{mealMeasure5: }>,
<{mealMeasure6: }>,
<{mealMeasure7: }>,
<{mealMeasure8: }>,
<{mealMeasure9: }>,
<{mealMeasure10: }>,
<{mealMeasure11: }>,
<{mealMeasure12: }>,
<{mealMeasure13: }>,
<{mealMeasure14: }>,
<{mealMeasure15: }>,
<{mealMeasure16: }>,
<{mealMeasure17: }>,
<{mealMeasure18: }>,
<{mealMeasure19: }>,
<{mealMeasure20: }>,
<{mealSource: }>,
<{dateModified: }>);
